# -*- coding: utf-8 -*-
"""Data Science Python Homework 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zj2wRYuVD4D-paKG_0T87wZbeUstVOBF
"""

S=(1,4,9,16,25,36)
print(S)

S=(15)
N1=0
N2=1
Next=N2
Count=1

while Count<=S:
  print(N1)
  Next=N1+N2
  N1=N2
  N2=Next
  Count+=1
print("End Sequence")

Word=("unanimously")
Count=0

for V in Word:
  if V=='a' or V=='e' or V=='i' or V=='o' or V=='u':
    Count+=1
    print(V)
print(Count)

N=142687
total=0

for X in str(N):
  total+=int(X)

print(total)

from datetime import datetime

CDT=datetime.now()

print(CDT)

Principle=1000
Rate=10
Time=1

CI=((Principle * pow((1 + Rate/100), Time)) - Principle)

print(CI)

Sentence="There are many ways to code with Python today"
count=0
Space=" "
for character in Sentence:
  if character in Space:
    count+=1
print(count)

N="234985080790"
count=0

for E in N:
  if E == '2' or E == '4' or E == '6' or E == '8' or E == '0':
    count+=1
    print(E)

print(E)

Number="123456789"

Swapped=Number[-1:]+Number[1:-1]+Number[0]

print(Swapped)

N="2645462"
Length=len(N)
I=0
F=Length-1

while I<F:
  if N[I]!=N[F]:
    print(N,"is not a Palindrome")
    break
  I+=1
  F-=1
else:
  print(N, "is a Palindrome")

N=3

for S in range(N):
  for X in range(N-S-1):
    print(" ", end="   ")
  for X in range(2*S+1):
    print("   *", end="")
  print()

Decimal=512

con={0: "0", 1: "1", 2: "2", 3: "3", 4: "4", 5: "5", 6: "6", 7: "7", 8: "8", 9: "9", 10: "A", 11: "B", 12: "C", 13: "D", 14: "E", 15: "F"}

def dectohex(Decimal):
  hex=''
  while Decimal>0:
    rem=Decimal%16
    hex=con[rem]+hex
    Decimal=Decimal//16
  return hex



print(dectohex(Decimal))

Animal=input("Enter an Animal: ")

for X in range(len(Animal)):
  OneString=Animal[-1:]+Animal[1:-1]+Animal[0]
  TwoString=Animal[0]+Animal[-1:]+Animal[1:-1]
  ThreeString=Animal[1:-1]+Animal[0]+Animal[-1:]
print(OneString)
print(TwoString)
print(ThreeString)

Flavor=input("Enter an Ice Cream Flavor: ")

print("Your ice cream flavor is {}!".format(Flavor))

File="Dog\nCat\nBus"
Line=2
X=0
SecondLine=""
for V in File:
  if X>Line:
    break
  else:
    if X==Line-1 and V!="\n":
      SecondLine+=V
    elif V=="\n":
      X+=1
print(SecondLine)

for prime in range(1,100):
  if prime>1:
    for X in range(2,prime):
      if prime%X==0:
        break
    else:
      print(prime)

Alphabet="abcdefghijklmnopqrstuvwxyz"

def replacement(Alphabet):
  Alternate=""
  for X in Alphabet:
    if X in "aeiou":
      Alternate+="1234"
    else:
      Alternate+=X
  return Alternate
NewAlphabet=replacement(Alphabet)
print(NewAlphabet)

Sentence="What time is it? The time is 2:30AM."

count1=0
count2=0
count3=0
count4=0
Lowercase="abcdefghijklmnopqrstuvwxyz"
Uppercase="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
Special="?.:"
Numbers="0123456789"

for char in Sentence:
  if char in Lowercase:
    count1+=1
print("Lowercase:", count1)

for char in Sentence:
  if char in Uppercase:
    count2+=1
print("Uppercase:", count2)

for char in Sentence:
  if char in Special:
    count3+=1
print("Special:", count3)

for char in Sentence:
  if char in Numbers:
    count4+=1
print("Numbers:", count4)

String="ABC123456ABC987654ABC062096"
Substring="ABC"
count=0
Sublen=len(Substring)

for O in range(len(String)):
  if String[O:O+Sublen]==Substring:
    count+=1
print(count)

List="AEIOU"

def Middle(List):
  Letter=int(len(List)/2)
  if len(List)%2==0:
    return List[Letter-1:Letter+1]
  else:
    return List[Letter]

print(Middle(List))